### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by kiaroa** [maateen/battery-monitor#44]
Getting this after different periods - crashes out.

 Traceback (most recent call last):
   File "/usr/share/battery-monitor/battery-monitor.py", line 215, in <module>
     notification = Notification("success")
   File "/usr/share/battery-monitor/battery-monitor.py", line 76, in __init__
     self.notifier.show()
 GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.Notifications' on object at path /org/freedesktop/Notifications (19)

Ubuntu 17.04

**Comment by kiaroa** [comment]
Another variation, after pulling the pwoer cord:
  File "/usr/share/battery-monitor/battery-monitor.py", line 221, in <module>
    notification.show_specific_notifications(monitor)
  File "/usr/share/battery-monitor/battery-monitor.py", line 193, in show_specific_notifications
    remaining_time=remaining)
  File "/usr/share/battery-monitor/battery-monitor.py", line 129, in show_notification
    self.notifier.show()
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.25 was not provided by any .service files (2)
Exception ignored in: <bound method Notification.__del__ of <__main__.Notification object at 0x7f661edf77f0>>
Traceback (most recent call last):
  File "/usr/share/battery-monitor/battery-monitor.py", line 198, in __del__
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.25 was not provided by any .service files (2)

**Comment by maateen** [comment]
How have you installed **Battery Monitor**? By PPA?

**Comment by kiaroa** [comment]
I was using develop. I've uninstalled and reinstalled using PPA, so I'll see what happens in the future. So far, removing/adding power cord has not recreated the issue :)

**Comment by maateen** [comment]
I haven't pushed the new update to PPA till now. After using PPA, make sure you have followed this: https://github.com/maateen/battery-monitor#for-beta-testers
