### ISSUE TITLE
Battery Monitor is not running 

### ISSUE THREAD

**Issue by msaworkstation** [maateen/battery-monitor#50]
Traceback (most recent call last):
  File "/usr/share/battery-monitor/battery-monitor.py", line 217, in <module>
    notification.show_specific_notifications(monitor)
  File "/usr/share/battery-monitor/battery-monitor.py", line 193, in show_specific_notifications
    remaining_time=remaining)
  File "/usr/share/battery-monitor/battery-monitor.py", line 131, in show_notification
    self.notifier.close()
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Failed:  (0)
Exception ignored in: <bound method Notification.__del__ of <__main__.Notification object at 0x7fc30cd61c18>>
Traceback (most recent call last):
  File "/usr/share/battery-monitor/battery-monitor.py", line 198, in __del__
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Failed:  (0)
mohamed@Mohamed-N5110:~$

**Comment by maateen** [comment]
Can you please run the following command on Terminal and paste the output here:

```
acpi -b
```

**Comment by msaworkstation** [comment]
Battery 0: Full, 100%

**Comment by maateen** [comment]
@msaworkstation Sorry to get back to you after a long time. We believe that installing `libnotify-cil-dev` package may solve your issue.

```
sudo apt-get install libnotify-cil-dev
```
