### ISSUE TITLE
AppIndicator.py wants python 3.6

### ISSUE THREAD

**Issue by soamaven** [maateen/battery-monitor#63]
Using `Ubuntu 16.04`, default `python` is 3.5.

`AppIndicator.py` uses the `typedef` syntax of 3.6.

So, 16.04 is not actually supported.

**Comment by yochananmarqos** [comment]
See [here](http://www.python36.com/install-python36-on-ubuntu/) for a tutorial for installing python-3.6 in Ubuntu 16.04. I recommend Step 3: **Install python 3.6 on Ubuntu 16.04 from PPA**.

**Comment by maateen** [comment]
@soamaven Installing Python3.6 won't fix the issue. You have to make a quick hack. You have to change python binary location (maybe, `/usr/bin/python3` to `/usr/local/bin/python3.6`) in these files:

- `/usr/local/bin/battery-monitor`
- `/etc/xdg/autostart/battery-monitor-autostart.desktop`
- `/usr/share/applications/battery-monitor.desktop`

We'll try to make a quick fix for you soon.

**Comment by mwamodojnr** [comment]
Can not make it work even with the changes.
```code
Traceback (most recent call last):
  File "/usr/share/battery-monitor/run.py", line 8, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'
```

**Comment by abspython** [comment]
I too have a similar problem in Debian Stretch ..Will this run in Python 3.7+??

**Comment by yochananmarqos** [comment]
It runs fine with Python 3.7 on Manjaro Linux here.

**Comment by abspython** [comment]
Well I installed Python 3.7 from source file and didn't work. I think I nee to change the python directories of the files as above mentioned by @maateen ..

**Comment by yochananmarqos** [comment]
Did you install from PPA or did you build from git? I'm running the git version.

**Comment by 0rkaM** [comment]
I was wondering if there is any fix coming for this issue.

**Comment by 0rkaM** [comment]
still nothing? this one is more than an year old...
