### ISSUE TITLE
Can't run after installation: SyntaxError

### ISSUE THREAD

**Issue by gkiril** [maateen/battery-monitor#73]
After installing on Ubuntu (with `sudo apt-get install battery-monitor -y`), when I try to run battery monitor from the command line, I get the following error:

```
$ battery-monitor
Traceback (most recent call last):
  File "/usr/share/battery-monitor/run.py", line 14, in <module>
    from AppIndicator import AppIndicator
  File "/usr/share/battery-monitor/AppIndicator.py", line 29
    TEST_MODE: bool
             ^
SyntaxError: invalid syntax
```
How can this be tackled?

**Comment by tomasvernercz** [comment]
Hello, I have the same problem.

**Comment by Mick3DIY** [comment]
Hello ! 
Same error after install or during restart... Strange ! :(

My system:
Ubuntu **16.04.5** LTS
Python **2.7.12** and Python **3.5.2**

Cheers !

**Comment by maateen** [comment]
We're very sorry to say that our very recent release comes with Python 3.6 compatibility only. It has broken previous Python 3.x versions compatibility. We have added a notice in our readme today.

Please allow us some time to come back with a solution. Also, please feel free to suggest/propose any solution. @gkiril @tomasvernercz @Mick3DIY

**Comment by Mick3DIY** [comment]
### Hi guys !
On my system, I have made some modifications for testing...

Add comments to the class in the files:

`class AppIndicator:  
    #TEST_MODE: bool`

`class BatteryMonitor:
    #raw_battery_info: str
    #processed_battery_info: Dict[str, str]`

`class Notification:
    #last_notification: str
    #last_percentage: int`

And it works (test mode, auto-start) !! :) It is Python specific version installed on my system ?

--> **Happy new year & best wishes !**  :yum:

**Comment by maateen** [comment]
@Mick3DIY Thanks for your reply. It's a hacky fix indeed. We are still looking for some long-term solution. Cheers!

**Comment by VipulRamtekkar** [comment]
@maateen. Is there a way around for this issue?

**Comment by maateen** [comment]
Yeah, upgrade your Python version.
